### ISSUE TITLE
update for new release?

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#1]
@mjg, since next stable version is about to be released ([info](http://git.ghostscript.com/?p=mupdf.git;a=blobdiff;f=CHANGES;h=5ea81f49ba6062511c7a7da06a1f6fb26fa51e66;hp=13c202a2b4a5554502e59afb7dfa6e3885fc71c6;hb=8cead7ac73de7f530b0b8af835690ecc92cb4bfa;hpb=77ca805ec3bb8c8b6edb3e7219d236ce00c07fb8)), I wonder whether it would be possible to update (or add a new `1.11` branch) the spec to this new version.

This is important to be able to test current master and report or confirm issues before the stable release.

Many thanks for your help.

**Comment by mjg** [comment]
Thanks for the ping. I've updated the spec based on the current official Fedora spec. You can find it in the v1.11 branch where I plan to follow the release candidates. So I'll close this issue.

Local builds work for me, and I have set up a copr repo [mjg/mupdf](https://copr.fedorainfracloud.org/coprs/mjg/mupdf/) now which builds for F25, F26 and rawhide (currently importing, may take a few hours with copr).
