### ISSUE TITLE
mupdf-1.16.1 released

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#10]
@mjg, mupdf-1.16.1 has been released.

Many thanks for your help.

**Comment by mjg** [comment]
Thanks for the ping, I had missed the rc completely. I'm building 1.16.1 right now. This will go (at least) to rawhide and F31. In fact, it's there ;)

**Comment by ousia** [comment]
I’m afraid I cannot find anything past 1.15 in:

* https://copr-be.cloud.fedoraproject.org/results/mjg/mupdf/
* https://copr.fedorainfracloud.org/coprs/mjg/mupdf/builds/
* https://copr.fedorainfracloud.org/coprs/mjg/mupdf/packages/

Sorry, but what am I missing here?

**Comment by ousia** [comment]
I’m still using FC 28, so I have to recompile the `.srpm` file.

I thought I would take a day or two as I read your reply in August.

But I totally forgot this. Today I have checked the version number and i remembered that I had to update.
