### ISSUE TITLE
MuPDF-1.17 released

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#11]
@mjg,

it seems that MuPDF-1.17 has been released recently (https://mupdf.com/release_history.html).

Many thanks for your work.

**Comment by mjg** [comment]
Hi @ousia 
mupdf 1.17 is now built in copr. Feel free to report here, I'll wait a bit before I push to rawhide.

**Comment by ousia** [comment]
Hi @mjg,

many thanks for the new build. It has some interesting improvements.

BTW, I have a question about the UI font.

MuPDF uses a serif font. In my opinion (my eyes always agree), a sans font would be way more readable.

I reported this issue in the past and they rejected the suggestion. I really appreciate that MuPDF could a sans font for UI text display.

Since MuPDF already uses serif (and I don’t want to change that), do you think it could be proposed as a compilation option?

Many thanks for your help.

**Comment by mjg** [comment]
My eyes completely agree with yours about UI fonts.
You care about the UI fonts for `mupdf-gl`, right? `mupdf-gl` is hardcoded to look for the builtin fonts `Charis SIL` and `Times` in file `platform/gl/gl-font.c`. I guess replacing `Charis SIL` there with, say, `DroidSans` should be as simple as a compile time option. Still weird that there is no config/command line option.

For FreeText annotations you can choose from different fonts. Strange design.

**Comment by ousia** [comment]
Many thanks for your reply.

I meant `mupdf-gl` only, since `mupdf-x11` lacks many features.

I’m going to report the issue again. Wish me luck.

**Comment by ousia** [comment]
@mjg, many thanks for adding version 1.17 to devel version.

Closing the issue myself.
