### ISSUE TITLE
version 1.17 segfaults with signed document

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#12]
Double-clicking on the signature annotation from https://kbdeveloper.qoppa.com/wp-content/uploads/blank_signed.pdf segfaults `mupdf-gl`.

I wonder whether [this commit](https://git.ghostscript.com/?p=mupdf.git;a=commit;h=a38556c13b132c2e3b275fac0d2e2f0f32895036) fixes the issue.

**Comment by mjg** [comment]
Thanks for the hint. I added the mentioned commit to 1.17.0-2 which is built in copr already and fixes the crash for me. I'll wait to see whether it fixes the crash for you, too, and push to rawhide then.

**Comment by ousia** [comment]
Many thanks for the new build. It fixes the issue for me.
