### ISSUE TITLE
stable 1.11 version released

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#4]
@mjg, would you be so kind to update both mupdf and mupdf-GL repos to latest stable release?

Many thanks for your help.

**Comment by mjg** [comment]
The Fedora spec switched to 1.11 now, including the GL build. Although the spec is a bit different from mine it would make sense to rebuild that for F25 (and use just one copr repo mupdf). What do you think?

**Comment by ousia** [comment]
I would say that it is better to have only one repo.

BTW, at least one of the mupdf developers has stated that Win32 and X11 will be deprecated in favor of the OpenGL.
