### ISSUE TITLE
new version 1.14-rc1

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#8]
@mjg,

version 1.13 has been released.

Just in case you might consider it, removing `thirdparty/freeglut` makes impossible to type non-ascii characters (#6).

Many thanks for your help.

**Comment by mjg** [comment]
Yes, that's what's in the copr build right now.
Unfortunately, the bundled freeglut does not seem to compile quite right on architectures with different endianness: https://koji.fedoraproject.org/koji/taskinfo?taskID=27039450

This delays the push of 1.13.0, unfortunately. I'll have to dig further.

**Comment by ousia** [comment]
According to https://mupdf.com/release_history.html, `mupdf-1.14.rc1` has been just released.

**Comment by ousia** [comment]
I forgot to mention, the build system seems to have been simplified:

- Auto-generated CMap, ICC, and JS source files are checked in to git.
- Embedded CMap resources are now generated by a python script.
- Embedded font resources are linked directly if using GNU ld or windows.
- Namegen tool replaced by use of C macros.
- Simplified Makefile.

Not sure whether this will improve packaging (I’m just ignorant on the details of these improvements).

**Comment by mjg** [comment]
Thanks for the ping. Alas, the build system changes break the package build for now. There are more fundamental changes than the ones outlined above, and they are not documented: the way in which thirdparty and system libraries are chosen is different now; builds seem to require mujs now (which is inherently unsafe); it builds two new libraries. Yes, I managed to build the beast meanwhile, but I have to make sure that this does not include unwanted bits.

**Comment by ousia** [comment]
Sorry to read that things are so different now.

I’m surprised also about `mujs` being inherently unsafe (it’s advertised as [_secure_](https://mujs.com/introduction.html)).

BTW, since `mupdf-gl` and `mupdf-x11` have such a feature mismatch (with annotations), I wonder whether it would make sense not to build `mupdf-x11` and link `mupdf` to `mupdf-gl`.

Just in case it helps.

**Comment by mjg** [comment]
mupdf-X11/gl still differ in key bindings, and the man page describes -X11. I don't mind using the "alternates" mechanism wher the user gets to decide which one is "mupdf", but I have to read up on how to package that.

As for "secure": I didn't mean to comment on the quality of mujs per se - it's just the notion of feeding scripts per PDF to an interpreter that runs on your machine that raises some alerts. It is not that different in ghostscript, where "SAFER" tries to distinguish between trusted and untrusted code. But I may be misreading the mujs scope completely. And we do ship the library in Fedora (just not a current version). copr test build for mupdf is coming today...

**Comment by ousia** [comment]
Many thanks for your explanation and for the test build coming today 👏.

BTW, wouldn’t it make sense to remove the `mjg/mupdf-GL` repository, since the `mjg/mupdf` repository includes both binaries?

**Comment by mjg** [comment]
It say "Starting with 1.11, builds off the official spec mjg/mupdf have the Open-GL based app so that this repo is obsoleted." in the mupdf-GL repo. I kept it for purposes of documentation/archival but don't mind removing it if it is confusing.

**Comment by mjg** [comment]
Builds looking OK so far.
