### ISSUE TITLE
OpenSSL not enabled

### ISSUE THREAD

**Issue by ousia** [mjg/mupdf.spec#9]
@mjg,

I tried to sign a [PDF document containing a signature field](https://github.com/mjg/mupdf.spec/files/2431886/signature-field.pdf) and I got a segmentation fault with an error about lacking OpenSSL support ([sample certificate](https://github.com/mjg/mupdf.spec/files/2431881/JohnDoe.pfx.txt) with password `123456`.)

Could you enable OpenSSL or do I have to report a bug upstream?

Many thanks for your help.

**Comment by mjg** [comment]
Interesting. New undocumented feature... But thank you for the test files!

The -3 version in copr is built with openssl now. That gets rid of the "no openssl support" error but core dumps anyways (besdies error about Sig widgets). (If I use the wrong password I get an error about that, then the core dump; with the correct password only the core dump).

It would be interesting to know if this works somewhere else.

**Comment by ousia** [comment]
It didn’t work in Windows, with the binaries provided by _Artifex_.

I opened a bug report with the proper backtrace and let’s see what happens.

I’m not closing the issue before the people from _Artifex_ answer my request.

**Comment by ousia** [comment]
Well, _Artifex_ released the stable version with no visible fix for the issue.

Well, I don’t know whether they might do anything to prevent the segmentation fault.

But for now, all I can say is that I don’t have any idea of [what _Artifex_ considers with the new feature](https://mupdf.com/release_history.html):

> * [c]an verify and sign digital signatures.

I must confess it is beyond my knowledge. But since this is an upstream issue, I’m closing this one.

**Comment by ousia** [comment]
The issue seems to be fixed [in current master](https://git.ghostscript.com/?p=mupdf.git;a=summary) .

Just in case you would be interested in packaging the current master.

**Comment by mjg** [comment]
Do you know which commit in master fixed that?

I'm hunting down a few of the fixes for current CVEs before I submit 1.14.0.

**Comment by mjg** [comment]
Never mind, I found it:
[gs bug](https://bugs.ghostscript.com/show_bug.cgi?id=699840)
[commit](http://www.ghostscript.com/cgi-bin/findgit.cgi?68840d4a34e1e56ea9130158e8e163fb60550db4)
